name: Build a specific version of Playwright

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Playwright version to build (e.g., 1.40.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write 
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set Playwright version
        run: |
          sed -i "s/^FROM mcr.microsoft.com\/playwright:.*/FROM mcr.microsoft.com\/playwright:${{ github.event.inputs.version }}/" Dockerfile
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}
