name: Build bun-compatible Playwright Docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Get docker image tag
        id: original_image
        run: |
          tag=$(grep ^FROM Dockerfile | cut -d ':' -f 2)
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/gwennlbh/playwright-bun:latest
            ghcr.io/gwennlbh/playwright-bun:${{ steps.original_image.outputs.tag }}
