name: Cleanup Docker images

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Docker image
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-tags: pr-*
